### ISSUE TITLE
loom files for velocity analysis ipynb

### ISSUE THREAD

**Issue by ttriche** [kirkeby-lab1/MiSTR-scRNAseq-data-analysis#1]
Hi, 

great paper and of interest for other purposes.  As such, do you have the .loom files used in the velocity analysis?  The dorsal patterning is of particular interest, but unfortunately I can't reproduce the analysis without the source data (SRA seems to have mangled the FASTQs, as it is wont to do with 10X data). 

Thanks!

**Comment by kirkeby-lab** [comment]
Hi,

Indeed .loom files can be provided. Please drop an e mail to gsr@sund.ku.dk and we can establish a secure channel to transfer data. 

Best,

**Comment by ttriche** [comment]
Thanks!  Email sent.
