### ISSUE TITLE
Would it possible to provide the ~/s_genes.csv and ~/g2m_genes.csv gene lists used in the RNA velocity notebook

### ISSUE THREAD

**Issue by bmlewis-UCSD** [kirkeby-lab1/MiSTR-scRNAseq-data-analysis#2]
# PROVIDE CELL CYCLE GENE LISTS FOR PHASE SCORING
S_genes_file = "~/s_genes.csv"
G2M_genes_file = "~/g2m_genes.csv"

**Comment by gauravsinghrathore** [comment]
it is the same as provided by seurat. 
https://satijalab.org/seurat/articles/cell_cycle_vignette.html

you can download the list from the link.

**Comment by bmlewis-UCSD** [comment]
Thank you!
